name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.
version: 0.3.3
publish_to: none


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    git:
      url: git@github.com:hungryemon/flutter-quill.git
      ref: 4bd3bc325b3dea4cc0d2d9116436c86004bc2722

  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  video_player: ^2.4.2
  youtube_player_flutter: ^8.1.1
  gallery_saver: ^2.3.2
  math_keyboard: ^0.2.0
  string_validator: ^1.0.0
  universal_html: ^2.2.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

# The following section is specific to Flutter packages.
flutter:
