name: flutter_quill_extensions
description: Embed extensions for flutter_quill including image, video, formula and etc.

version: 0.4.1
publish_to: none


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_quill:
    git:
      url: git@github.com:hungryemon/flutter-quill.git
      ref: 4d531de83ec322c031bfd9a6cccb5827dfe858b4


  image_picker: ">=0.8.5 <2.0.0"
  photo_view: ^0.14.0
  # video_player: ^2.4.2
  # youtube_player_flutter: ^8.1.2

  gallery_saver: #^3.0.1
   git: 
    url: git@github.com:hungryemon/gallery_saver.git
    branch: emon
    ref: 13f218e1badecae0361a46913ed0570d8a4d5494
  math_keyboard: ">=0.1.8 <0.3.0"
  string_validator: ^1.0.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
